- 각 차원을 의미하는 axis
- ex) 2차원 행렬이라면 0,1을 기본값으로 가지고 있다.
- 아무것도 명시하지 않다면 기본값은 전체를 둠

In [1]:
import numpy as np

### numpy 이해하기
- 몇몇 함수에는 axis keyword 파라미터가 존재(거의 대부분의 연산 함수)
- axis값이 없는 경우에는 전체 데이터에 대해 적용
- axis값이 있는 경우에는 **해당 axis를 따라서 적용**
  - 따라서 결과는 해당 axis가 제외된 나머지 차원의 데이터만 남게 됨

In [2]:
x=np.arange(15)

In [3]:
np.sum(x)

105

In [5]:
np.sum(x,axis=0) #축이 1개라는 의미
#-1차원 벡터는 축이 존재하지 않는다.
#axis=1이라면 존재하지 않은 축에 대해 적용하였기 때문에 오류가 발생

105

In [7]:
y=x.reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- 행이 증가하는 방향이 1
- 열이 증가하는 방향이 0(1차원의 기본값을 기억하면서)

In [8]:
np.sum(y,axis=1) #각 행의 합을 리스트 형태로 저장

array([10, 35, 60])

In [9]:
np.sum(y,axis=0) #각 열의 합을 리스트 형태로 저장

array([15, 18, 21, 24, 27])

In [11]:
z=np.arange(36).reshape(3,4,3)
print(z)
np.sum(z,axis=0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [12]:
np.sum(z,axis=1)

array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [13]:
np.sum(z,axis=2)
#np.sum(z,axis=-1) #음수도 지원하긴 하다만 비추천

array([[  3,  12,  21,  30],
       [ 39,  48,  57,  66],
       [ 75,  84,  93, 102]])

- axis의 값이 튜플일 경우
  - 해당 튜플에 명시된 모든 axis에 대해서 연산

In [14]:
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [15]:
np.sum(z,axis=(0,1)) #두 면을 합쳐서 표현할수도 있음

array([198, 210, 222])

- pandas의 값은 기본적으로 2차원 행렬
  - 0과1 의 axis를 가지고 있음에 주의