### numpy documentation
- [numpy 공식 문서 링크](https://numpy.org/doc/stable/reference/index.html)
- numpy에서 제공되는 함수 등에 관한 문서

In [2]:
import numpy as np

In [7]:
x=np.arange(15).reshape(3,5)
y=np.random.randint(1,100,15).reshape(3,5)
print(x)
print(y)
#연산을 위한 예제 행렬 생성

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[31 66 75 57 99]
 [24 68 99 47 15]
 [32 45 91 52 36]]


### 연산 함수
- add, substract, multiply, divide
- 기존 연산자를 사용해서도 이용 가능

In [8]:
np.add(x,y)

array([[ 31,  67,  77,  60, 103],
       [ 29,  74, 106,  55,  24],
       [ 42,  56, 103,  65,  50]])

In [9]:
np.subtract(x,y)

array([[-31, -65, -73, -54, -95],
       [-19, -62, -92, -39,  -6],
       [-22, -34, -79, -39, -22]])

In [10]:
np.multiply(x,y)

array([[   0,   66,  150,  171,  396],
       [ 120,  408,  693,  376,  135],
       [ 320,  495, 1092,  676,  504]])

In [11]:
np.divide(x,y)

array([[0.        , 0.01515152, 0.02666667, 0.05263158, 0.04040404],
       [0.20833333, 0.08823529, 0.07070707, 0.17021277, 0.6       ],
       [0.3125    , 0.24444444, 0.13186813, 0.25      , 0.38888889]])

### 통계 함수
- 평균, 분산, 중앙, 최대, 최소값 등 통계 관련 함수 내장
- loop를 이용한 계산을 거의 하지 않을 것(야호)

In [12]:
np.mean(y)#평균 구하는 방법 1
y.mean()#평균 구하는 방법 2

55.8

In [13]:
np.max(y)#최댓값 구하기

99

In [14]:
np.argmax(y)#최댓값의 인덱스 구하기
#flatten한 상태(1차원)로 인식하여 인덱싱

4

In [15]:
np.var(y)#분산

670.16

In [16]:
np.median(y)#중앙값

52.0

In [17]:
np.std(y)#표준편차

25.887448696231154

### 집계 함수
- 합계(sum), 누적 합계(cumsum) 등 계산 가능

In [18]:
np.sum(y) #전체의 합

837

In [19]:
np.cumsum(y) #인덱스의 누적합

array([ 31,  97, 172, 229, 328, 352, 420, 519, 566, 581, 613, 658, 749,
       801, 837], dtype=int32)

### any, all 함수
- any : 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
- all : 모든 원소가 특정 조건을 만족하면 True, 아니면 False

In [21]:
z=np.random.randn(10)
print(z)

[ 0.23034397  2.63331615 -0.65378328 -1.18460998 -0.64430981  1.46921394
 -3.57096456  0.81175123  2.13096861 -0.48904095]


In [24]:
z>0 #이짝에도 대소 비교 연산자 사용 가능

array([ True,  True, False, False, False,  True, False,  True,  True,
       False])

In [23]:
np.any(z>0) #하나라도 참이 있어서 True

True

In [26]:
np.all(z>0) #하나라도 거짓이 있어서 False

False

In [27]:
np.all(z!=0)

True

### where 함수
- 조건에 따라 선별적으로 값을 선택 가능
- ex) 음수인 경우 0, 나머지느 그대로 값을 쓰는 경우
- 파라미터 : np.where(**조건, 참인 경우 수식, 거짓인 경우 수식**)

In [29]:
z=np.random.randn(10)
print(z)

[ 1.41968395 -0.05181132 -2.05035214 -1.82322885 -0.43435361  2.01140543
  0.99591854 -1.67840818 -0.97716628 -0.29068835]


In [31]:
np.where(z>0,z,0) #모든 값에 대해 0보다 크다면 그대로 사용, 아니면 0으로 바꾸기

array([1.41968395, 0.        , 0.        , 0.        , 0.        ,
       2.01140543, 0.99591854, 0.        , 0.        , 0.        ])