In [2]:
import numpy as np

### 인덱싱
- 파이썬 리스트와 동일한 개념으로 사용
- ,를 사용하여 각 차원의 인덱스에 접근 가능

In [33]:
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
x[0]

0

In [35]:
x[-1]

9

In [36]:
x[3]=100#값의 변경도 가능
print(x)

[  0   1   2 100   4   5   6   7   8   9]


In [37]:
x=x.reshape(2,5)
print(x)

[[  0   1   2 100   4]
 [  5   6   7   8   9]]


In [38]:
x[0][1]#1번째 행의 2번째 열 값을 출력

1

In [39]:
x[1,2]

7

In [40]:
x[1][2]#여러 가지 방법을 이용해서도 접근 가능

7

In [41]:
y=np.arange(36).reshape(3,4,3)#n차원 행렬에 대해서도 생성/접근이 가능
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [43]:
y[1][2]
#y[1,2]와 같은 의미

array([18, 19, 20])

### 슬라이싱
- 리스트, 문자열 slicing과 동일한 개념으로 사용
- ,를 사용하여 각 차원 별로 슬라이싱 가능
- 슬라이싱을 한다고 해도 차원이 변하지는 않는다.

In [44]:
x1=np.arange(10)
print(x1)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
x1[1:7]

array([1, 2, 3, 4, 5, 6])

In [47]:
x2=np.arange(10).reshape(2,5)
print(x2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


- 슬라이싱의 결과로 대괄호가 2개가 보인다는 것=**차원이 변하지 않는다.**
- **인덱싱은 차원이 변한다**

In [49]:
x2[1][1:4] #다음과 같은 형식으로 n차원에 대해 부분 슬라이싱이 가능

array([6, 7, 8])

In [57]:
x2[:,:2] #모든 행에 대해 두번째 열을 출력
#x2[:2][:2]은 지원하지 않는 듯 하다.

array([[0, 1],
       [5, 6]])

- 3차원 슬라이싱 과정

In [58]:
x3=np.arange(54).reshape(2,9,3)
print(x3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [59]:
x3[:1,:2,:]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [61]:
x3[0,:2,:] #차원이 바뀌는 것에 유의

array([[0, 1, 2],
       [3, 4, 5]])