### Boolean indexing
- ndarray 인덱싱 시, bool 리스트를 전달하여 True인 경우에만 필터링

- 브로드캐스팅을 활용하여 ndarray로부터 bool list 얻기
  - ex) 짝수인 경우만 찾아보기

In [1]:
import numpy as np

In [2]:
x=np.random.randint(1,100,size=10)
print(x)

[94 69 89 80 36 50 44 67  8 42]


In [4]:
mask=x%2==0

- 위의 리스트를 인덱스로 전달해보자

In [6]:
x[mask] #True인 인덱스에 한해서만 출력이 된 것을 확인할 수 있다.

array([94, 80, 36, 50, 44,  8, 42])

In [7]:
x[x%2==0] #위와 같은 형태임.

array([94, 80, 36, 50, 44,  8, 42])

In [8]:
x[x>30]

array([94, 69, 89, 80, 36, 50, 44, 67, 42])

### 다중조건 사용
- 파이썬 논리 연산자인 and, or, not 사용은 불가능
- &(and), |(or)을 사용한다.

In [10]:
x[(x%2==0)&(x>30)]

array([94, 80, 36, 50, 44, 42])

In [11]:
x[(x>60)|(x<30)]

array([94, 69, 89, 80, 67,  8])

### 예제. 2019년 7월 서울 평균기온 데이터
- 평균기온이 25도를 넘는 날수는?
- 평균기온이 25를 넘는 남의 평균 기온은?

In [12]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [19]:
np.count_nonzero(temp>25)

21

In [20]:
len(temp)

31

In [23]:
np.average(temp[temp>25])#temp 리스트로 한 번 걸어주어야 함
#mean을 써도 무방. 이 둘의 미묘한 차이가 있기는 함

26.857142857142858