In [4]:
import numpy as np

### np.linalg.inv
- 역행렬을 구할 때 사용
- 모든 차원의 값이 같아야 함

In [5]:
x=np.random.randint(100,size=(3,3))
print(x)
x@np.linalg.inv(x)

[[48  6 84]
 [ 6 76 48]
 [25 26 37]]


array([[ 1.00000000e+00, -4.16333634e-17, -1.38777878e-16],
       [ 5.55111512e-17,  1.00000000e+00, -3.33066907e-16],
       [ 1.07552856e-16, -1.76941795e-16,  1.00000000e+00]])

### np.linalg.solve
- Ax=B 형태의 선형대수식 솔루션을 제공
- ex)
  - x+y=25
  - 2x+4y=64

In [6]:
A=np.array([[1,1],[2,4]])
B=([25,64])
x=np.linalg.solve(A,B)#행렬의 x값을 찾아낼 수 있음
print(x)

print(A@x)
np.allclose(A@x,B) #이 수식이 맞는지 확인

[18.  7.]
[25. 64.]


True

In [7]:
print(A)

[[1 1]
 [2 4]]
